framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            order:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\OrderSerializer
                options:
                    queues:
                        order:
                            binding_keys: []

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Messenger\OrderMessage: order
