framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            order:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\Order\ImportOrderMessageSerializer
                options:
                    queues:
                        order:
                            binding_keys: []
            deliveryNote:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\DeliveryNote\ImportDeliveryNoteMessageSerializer
                options:
                    queues:
                        order:
                            binding_keys: [ ]

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Messenger\Order\ImportOrderMessage: order
            App\Messenger\DeliveryNote\ImportDeliveryNoteMessage: order
